import { defineStore } from 'pinia';
import type { CreateOrderRequest, OrderView } from '@bake-mall/contracts';

import { ordersApi } from '../api/orders.js';

type OrdersState = {
  items: OrderView[];
  current: OrderView | null;
  loading: boolean;
  submitting: boolean;
  lastError: string | null;
};

/**
 * Customer-side order history store.
 *
 * - `refresh()` pulls the latest orders for the current user via
 *   `GET /me/orders`.
 * - `loadOne(id)` fetches a single order via `GET /me/orders/:id`. The
 *   endpoint returns the immutable `OrderView` so the detail screen never
 *   needs to reach back into the live catalog.
 * - `create(body, idempotencyKey)` calls `POST /orders` with the supplied
 *   `Idempotency-Key` header. The idempotency key is generated by the
 *   checkout view and reused across retries so a flaky network never
 *   results in a duplicate order. The store deliberately does NOT mint
 *   its own key — the checkout view owns key generation so retries can
 *   reuse the same value.
 */
export const useOrdersStore = defineStore('orders', {
  state: (): OrdersState => ({
    items: [],
    current: null,
    loading: false,
    submitting: false,
    lastError: null,
  }),
  actions: {
    async refresh(): Promise<OrderView[]> {
      this.loading = true;
      this.lastError = null;
      try {
        const items = await ordersApi.listMine();
        this.items = items;
        return items;
      } catch (error) {
        this.lastError = error instanceof Error ? error.message : '加载失败';
        throw error;
      } finally {
        this.loading = false;
      }
    },

    async loadOne(id: string): Promise<OrderView> {
      this.loading = true;
      this.lastError = null;
      try {
        const order = await ordersApi.getMine(id);
        this.current = order;
        return order;
      } catch (error) {
        this.lastError = error instanceof Error ? error.message : '加载失败';
        throw error;
      } finally {
        this.loading = false;
      }
    },

    async create(
      body: CreateOrderRequest,
      idempotencyKey: string,
    ): Promise<OrderView> {
      this.submitting = true;
      this.lastError = null;
      try {
        const order = await ordersApi.create(body, idempotencyKey);
        this.current = order;
        return order;
      } catch (error) {
        this.lastError = error instanceof Error ? error.message : '提交失败';
        throw error;
      } finally {
        this.submitting = false;
      }
    },
  },
});

export type OrdersStore = ReturnType<typeof useOrdersStore>;
