export enum OrderStatus {
  NEW = 'NEW',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum FulfillmentType {
  PICKUP = 'PICKUP',
  DELIVERY = 'DELIVERY',
}

export enum BannerTargetType {
  NONE = 'NONE',
  PRODUCT = 'PRODUCT',
  CATEGORY = 'CATEGORY',
}

export enum AdminOrderExportView {
  ORDER = 'ORDER',
  SUPPLY = 'SUPPLY',
}

export enum AdminOrderSupplyMatchType {
  SKU_ID = 'SKU_ID',
  LEGACY_FALLBACK = 'LEGACY_FALLBACK',
}

export enum AdminRole {
  SUPER_ADMIN = 'SUPER_ADMIN',
  OPERATOR = 'OPERATOR',
}

export enum AdminPermission {
  ORDER_READ = 'ORDER_READ',
  ORDER_STATUS_UPDATE = 'ORDER_STATUS_UPDATE',
  USER_READ = 'USER_READ',
  USER_CREATE = 'USER_CREATE',
  PRINT_DEVICE_MANAGE = 'PRINT_DEVICE_MANAGE',
  PRINT_EXECUTE = 'PRINT_EXECUTE',
  PRINT_HISTORY_READ = 'PRINT_HISTORY_READ',
  SELF_PASSWORD_CHANGE = 'SELF_PASSWORD_CHANGE',
}

export enum CloudPrinterStatus {
  BINDING = 'BINDING',
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
  ACTIVE = 'ACTIVE',
  UNBINDING = 'UNBINDING',
  UNBOUND = 'UNBOUND',
  ERROR = 'ERROR',
}

export enum CloudPrinterOnlineStatus {
  UNKNOWN = 'UNKNOWN',
  OFFLINE = 'OFFLINE',
  ONLINE = 'ONLINE',
  ABNORMAL = 'ABNORMAL',
}

export enum VendorRelationState {
  UNKNOWN = 'UNKNOWN',
  CONFIRMED_BOUND = 'CONFIRMED_BOUND',
  CONFIRMED_UNBOUND = 'CONFIRMED_UNBOUND',
}

export enum PrinterBindingStage {
  NONE = 'NONE',
  ADD_PRINTER = 'ADD_PRINTER',
  PRINT_VERIFICATION_CODE = 'PRINT_VERIFICATION_CODE',
  COMPENSATION_DELETE = 'COMPENSATION_DELETE',
  UNBIND_DELETE = 'UNBIND_DELETE',
  RECONCILIATION = 'RECONCILIATION',
}

export enum PrintBatchStatus {
  DRAFT = 'DRAFT',
  READY = 'READY',
  RUNNING = 'RUNNING',
  PAUSED = 'PAUSED',
  COMPLETED = 'COMPLETED',
  COMPLETED_WITH_ISSUES = 'COMPLETED_WITH_ISSUES',
  CANCELLED = 'CANCELLED',
}

export enum PrintJobStatus {
  PENDING = 'PENDING',
  SUBMITTING = 'SUBMITTING',
  /** 厂商已接受提交意图，不代表小票已经物理出纸。 */
  ACCEPTED = 'ACCEPTED',
  FAILED = 'FAILED',
  UNKNOWN = 'UNKNOWN',
  MANUAL_REVIEW = 'MANUAL_REVIEW',
  MANUALLY_CONFIRMED_PRINTED = 'MANUALLY_CONFIRMED_PRINTED',
  MANUALLY_CLOSED = 'MANUALLY_CLOSED',
  CANCELLED = 'CANCELLED',
}

export enum ManualPrintResolution {
  CONFIRM_PRINTED = 'CONFIRM_PRINTED',
  CONFIRM_NOT_PRINTED = 'CONFIRM_NOT_PRINTED',
  RETRY_WITH_DUPLICATE_RISK = 'RETRY_WITH_DUPLICATE_RISK',
}

export enum ApiErrorCode {
  PHONE_REQUIRED = 'PHONE_REQUIRED',
  ORDER_CONTACT_PHONE_REQUIRED = 'ORDER_CONTACT_PHONE_REQUIRED',
  ORDER_CONTACT_PHONE_VERSION_CONFLICT = 'ORDER_CONTACT_PHONE_VERSION_CONFLICT',
  ORDER_CONTACT_PHONE_UPDATE_VERSION_CONFLICT = 'ORDER_CONTACT_PHONE_UPDATE_VERSION_CONFLICT',
  SKU_UNAVAILABLE = 'SKU_UNAVAILABLE',
  STOCK_INSUFFICIENT = 'STOCK_INSUFFICIENT',
  INVALID_ORDER_TRANSITION = 'INVALID_ORDER_TRANSITION',
  PRODUCT_STOCK_CONFLICT = 'PRODUCT_STOCK_CONFLICT',
  PRODUCT_ASSET_OWNERSHIP_INVALID = 'PRODUCT_ASSET_OWNERSHIP_INVALID',
  MEMBERSHIP_LEVEL_NOT_FOUND = 'MEMBERSHIP_LEVEL_NOT_FOUND',
  MEMBERSHIP_LEVEL_INACTIVE = 'MEMBERSHIP_LEVEL_INACTIVE',
  MEMBERSHIP_DOWNGRADE_NOT_ALLOWED = 'MEMBERSHIP_DOWNGRADE_NOT_ALLOWED',
  MEMBERSHIP_LEVEL_VERSION_CONFLICT = 'MEMBERSHIP_LEVEL_VERSION_CONFLICT',
  MEMBERSHIP_LEVEL_CONFLICT = 'MEMBERSHIP_LEVEL_CONFLICT',
  MEMBERSHIP_PURCHASE_NOT_VOIDABLE = 'MEMBERSHIP_PURCHASE_NOT_VOIDABLE',
  MEMBERSHIP_PURCHASE_NOT_FOUND = 'MEMBERSHIP_PURCHASE_NOT_FOUND',
  MEMBERSHIP_PURCHASE_NOT_PAYABLE = 'MEMBERSHIP_PURCHASE_NOT_PAYABLE',
  MEMBERSHIP_ENTITLEMENT_INCONSISTENT = 'MEMBERSHIP_ENTITLEMENT_INCONSISTENT',
  SIMULATED_PAYMENT_DISABLED = 'SIMULATED_PAYMENT_DISABLED',
  MEMBER_CREDIT_INSUFFICIENT = 'MEMBER_CREDIT_INSUFFICIENT',
  MEMBER_CREDIT_INCONSISTENT = 'MEMBER_CREDIT_INCONSISTENT',
  ORDER_QUOTE_STALE = 'ORDER_QUOTE_STALE',
  IDEMPOTENCY_IN_PROGRESS = 'IDEMPOTENCY_IN_PROGRESS',
  IDEMPOTENCY_CONFLICT = 'IDEMPOTENCY_CONFLICT',
  EXPORT_TOO_LARGE = 'EXPORT_TOO_LARGE',
  EXPORT_IN_PROGRESS = 'EXPORT_IN_PROGRESS',
  HOMEPAGE_VERSION_CONFLICT = 'HOMEPAGE_VERSION_CONFLICT',
  HOMEPAGE_PUBLISH_INVALID = 'HOMEPAGE_PUBLISH_INVALID',
  HOMEPAGE_ASSET_OWNERSHIP_INVALID = 'HOMEPAGE_ASSET_OWNERSHIP_INVALID',
  HOMEPAGE_DRAFT_NOT_FOUND = 'HOMEPAGE_DRAFT_NOT_FOUND',
  HOMEPAGE_DRAFT_NAME_CONFLICT = 'HOMEPAGE_DRAFT_NAME_CONFLICT',
  HOMEPAGE_PUBLISHED_DRAFT_DELETE_FORBIDDEN = 'HOMEPAGE_PUBLISHED_DRAFT_DELETE_FORBIDDEN',
  USER_MERGE_REQUIRES_MANUAL_REVIEW = 'USER_MERGE_REQUIRES_MANUAL_REVIEW',
  WECHAT_IDENTITY_CONFLICT = 'WECHAT_IDENTITY_CONFLICT',
  ADMIN_USER_CONFLICT = 'ADMIN_USER_CONFLICT',
  ADMIN_LOGIN_PHONE_CONFLICT = 'ADMIN_LOGIN_PHONE_CONFLICT',
  ADMIN_PASSWORD_CHANGE_REQUIRED = 'ADMIN_PASSWORD_CHANGE_REQUIRED',
  ADMIN_PASSWORD_POLICY_VIOLATION = 'ADMIN_PASSWORD_POLICY_VIOLATION',
  ADMIN_VERIFICATION_FAILED = 'ADMIN_VERIFICATION_FAILED',
  ADMIN_VERIFICATION_RATE_LIMITED = 'ADMIN_VERIFICATION_RATE_LIMITED',
  ADMIN_PERMISSION_DENIED = 'ADMIN_PERMISSION_DENIED',
  WECHAT_CREDENTIAL_REPLAYED = 'WECHAT_CREDENTIAL_REPLAYED',
  WECHAT_CREDENTIAL_IN_PROGRESS = 'WECHAT_CREDENTIAL_IN_PROGRESS',
  WECHAT_AUTH_FAILED = 'WECHAT_AUTH_FAILED',
  WECHAT_SERVICE_UNAVAILABLE = 'WECHAT_SERVICE_UNAVAILABLE',
  CLOUD_PRINTER_SERIAL_INVALID = 'CLOUD_PRINTER_SERIAL_INVALID',
  CLOUD_PRINTER_NAME_INVALID = 'CLOUD_PRINTER_NAME_INVALID',
  CLOUD_PRINTER_ALREADY_BOUND = 'CLOUD_PRINTER_ALREADY_BOUND',
  CLOUD_PRINTER_OWNERSHIP_CONFLICT = 'CLOUD_PRINTER_OWNERSHIP_CONFLICT',
  CLOUD_PRINTER_VENDOR_LIMIT = 'CLOUD_PRINTER_VENDOR_LIMIT',
  CLOUD_PRINTER_VENDOR_RATE_LIMITED = 'CLOUD_PRINTER_VENDOR_RATE_LIMITED',
  CLOUD_PRINTER_VERIFICATION_CODE_INVALID = 'CLOUD_PRINTER_VERIFICATION_CODE_INVALID',
  CLOUD_PRINTER_VERIFICATION_EXPIRED = 'CLOUD_PRINTER_VERIFICATION_EXPIRED',
  CLOUD_PRINTER_VERIFICATION_ATTEMPTS_EXHAUSTED = 'CLOUD_PRINTER_VERIFICATION_ATTEMPTS_EXHAUSTED',
  CLOUD_PRINTER_OFFLINE = 'CLOUD_PRINTER_OFFLINE',
  CLOUD_PRINTER_ONLINE_STATUS_UNKNOWN = 'CLOUD_PRINTER_ONLINE_STATUS_UNKNOWN',
  CLOUD_PRINTER_BINDING_RECOVERY_REQUIRED = 'CLOUD_PRINTER_BINDING_RECOVERY_REQUIRED',
  CLOUD_PRINTER_COMPENSATION_RECOVERY_REQUIRED = 'CLOUD_PRINTER_COMPENSATION_RECOVERY_REQUIRED',
  CLOUD_PRINTER_RECOVERY_REQUIRED = 'CLOUD_PRINTER_RECOVERY_REQUIRED',
  CLOUD_PRINTER_VENDOR_REJECTED = 'CLOUD_PRINTER_VENDOR_REJECTED',
  CLOUD_PRINTER_VENDOR_UNAVAILABLE = 'CLOUD_PRINTER_VENDOR_UNAVAILABLE',
  CLOUD_PRINTER_UNBIND_BLOCKED = 'CLOUD_PRINTER_UNBIND_BLOCKED',
  CLOUD_PRINTER_NOT_FOUND = 'CLOUD_PRINTER_NOT_FOUND',
  CLOUD_PRINTER_CURRENT_INELIGIBLE = 'CLOUD_PRINTER_CURRENT_INELIGIBLE',
  CLOUD_PRINTER_CURRENT_VERSION_CONFLICT = 'CLOUD_PRINTER_CURRENT_VERSION_CONFLICT',
  CLOUD_PRINTER_CURRENT_UNBIND_FORBIDDEN = 'CLOUD_PRINTER_CURRENT_UNBIND_FORBIDDEN',
  PRINT_ORDER_NOT_PRINTABLE = 'PRINT_ORDER_NOT_PRINTABLE',
  PRINT_BATCH_NOT_FOUND = 'PRINT_BATCH_NOT_FOUND',
  PRINT_BATCH_STATUS_CONFLICT = 'PRINT_BATCH_STATUS_CONFLICT',
  PRINT_BATCH_APPEND_LIMIT_EXCEEDED = 'PRINT_BATCH_APPEND_LIMIT_EXCEEDED',
  PRINT_BATCH_LEASE_CONFLICT = 'PRINT_BATCH_LEASE_CONFLICT',
  PRINT_JOB_NOT_FOUND = 'PRINT_JOB_NOT_FOUND',
  PRINT_JOB_STATUS_CONFLICT = 'PRINT_JOB_STATUS_CONFLICT',
  PRINT_JOB_RESULT_UNKNOWN = 'PRINT_JOB_RESULT_UNKNOWN',
  PRINT_JOB_MANUAL_REVIEW_REQUIRED = 'PRINT_JOB_MANUAL_REVIEW_REQUIRED',
  PRINT_JOB_PAYLOAD_REDACTED = 'PRINT_JOB_PAYLOAD_REDACTED',
  IDEMPOTENCY_RESULT_UNKNOWN = 'IDEMPOTENCY_RESULT_UNKNOWN',
}
