export enum OrderStatus {
  NEW = 'NEW',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
}

export enum FulfillmentType {
  PICKUP = 'PICKUP',
  DELIVERY = 'DELIVERY',
}

export enum BannerTargetType {
  NONE = 'NONE',
  PRODUCT = 'PRODUCT',
  CATEGORY = 'CATEGORY',
}

export enum AdminOrderExportView {
  ORDER = 'ORDER',
  SUPPLY = 'SUPPLY',
}

export enum AdminOrderSupplyMatchType {
  SKU_ID = 'SKU_ID',
  LEGACY_FALLBACK = 'LEGACY_FALLBACK',
}

export enum ApiErrorCode {
  PHONE_REQUIRED = 'PHONE_REQUIRED',
  SKU_UNAVAILABLE = 'SKU_UNAVAILABLE',
  STOCK_INSUFFICIENT = 'STOCK_INSUFFICIENT',
  INVALID_ORDER_TRANSITION = 'INVALID_ORDER_TRANSITION',
  PRODUCT_STOCK_CONFLICT = 'PRODUCT_STOCK_CONFLICT',
  PRODUCT_ASSET_OWNERSHIP_INVALID = 'PRODUCT_ASSET_OWNERSHIP_INVALID',
  MEMBERSHIP_LEVEL_NOT_FOUND = 'MEMBERSHIP_LEVEL_NOT_FOUND',
  MEMBERSHIP_LEVEL_INACTIVE = 'MEMBERSHIP_LEVEL_INACTIVE',
  MEMBERSHIP_DOWNGRADE_NOT_ALLOWED = 'MEMBERSHIP_DOWNGRADE_NOT_ALLOWED',
  MEMBERSHIP_LEVEL_VERSION_CONFLICT = 'MEMBERSHIP_LEVEL_VERSION_CONFLICT',
  MEMBERSHIP_LEVEL_CONFLICT = 'MEMBERSHIP_LEVEL_CONFLICT',
  MEMBERSHIP_PURCHASE_NOT_VOIDABLE = 'MEMBERSHIP_PURCHASE_NOT_VOIDABLE',
  MEMBERSHIP_PURCHASE_NOT_FOUND = 'MEMBERSHIP_PURCHASE_NOT_FOUND',
  MEMBERSHIP_PURCHASE_NOT_PAYABLE = 'MEMBERSHIP_PURCHASE_NOT_PAYABLE',
  MEMBERSHIP_ENTITLEMENT_INCONSISTENT = 'MEMBERSHIP_ENTITLEMENT_INCONSISTENT',
  SIMULATED_PAYMENT_DISABLED = 'SIMULATED_PAYMENT_DISABLED',
  MEMBER_CREDIT_INSUFFICIENT = 'MEMBER_CREDIT_INSUFFICIENT',
  MEMBER_CREDIT_INCONSISTENT = 'MEMBER_CREDIT_INCONSISTENT',
  ORDER_QUOTE_STALE = 'ORDER_QUOTE_STALE',
  IDEMPOTENCY_IN_PROGRESS = 'IDEMPOTENCY_IN_PROGRESS',
  IDEMPOTENCY_CONFLICT = 'IDEMPOTENCY_CONFLICT',
  EXPORT_TOO_LARGE = 'EXPORT_TOO_LARGE',
  EXPORT_IN_PROGRESS = 'EXPORT_IN_PROGRESS',
  HOMEPAGE_VERSION_CONFLICT = 'HOMEPAGE_VERSION_CONFLICT',
  HOMEPAGE_PUBLISH_INVALID = 'HOMEPAGE_PUBLISH_INVALID',
  HOMEPAGE_ASSET_OWNERSHIP_INVALID = 'HOMEPAGE_ASSET_OWNERSHIP_INVALID',
}
