import { ApiErrorCode } from './enums.js';

export type IdentityApiErrorCode =
  | ApiErrorCode.USER_MERGE_REQUIRES_MANUAL_REVIEW
  | ApiErrorCode.WECHAT_IDENTITY_CONFLICT
  | ApiErrorCode.ADMIN_USER_CONFLICT
  | ApiErrorCode.ADMIN_PASSWORD_CHANGE_REQUIRED
  | ApiErrorCode.ADMIN_PASSWORD_POLICY_VIOLATION
  | ApiErrorCode.ADMIN_VERIFICATION_FAILED
  | ApiErrorCode.ADMIN_VERIFICATION_RATE_LIMITED
  | ApiErrorCode.ADMIN_PERMISSION_DENIED
  | ApiErrorCode.WECHAT_CREDENTIAL_REPLAYED
  | ApiErrorCode.WECHAT_CREDENTIAL_IN_PROGRESS
  | ApiErrorCode.WECHAT_AUTH_FAILED
  | ApiErrorCode.WECHAT_SERVICE_UNAVAILABLE;

export type PrintingApiErrorCode =
  | ApiErrorCode.ADMIN_VERIFICATION_FAILED
  | ApiErrorCode.ADMIN_VERIFICATION_RATE_LIMITED
  | ApiErrorCode.ADMIN_PERMISSION_DENIED
  | ApiErrorCode.CLOUD_PRINTER_SERIAL_INVALID
  | ApiErrorCode.CLOUD_PRINTER_NAME_INVALID
  | ApiErrorCode.CLOUD_PRINTER_ALREADY_BOUND
  | ApiErrorCode.CLOUD_PRINTER_OWNERSHIP_CONFLICT
  | ApiErrorCode.CLOUD_PRINTER_VENDOR_LIMIT
  | ApiErrorCode.CLOUD_PRINTER_VENDOR_RATE_LIMITED
  | ApiErrorCode.CLOUD_PRINTER_VERIFICATION_CODE_INVALID
  | ApiErrorCode.CLOUD_PRINTER_VERIFICATION_EXPIRED
  | ApiErrorCode.CLOUD_PRINTER_VERIFICATION_ATTEMPTS_EXHAUSTED
  | ApiErrorCode.CLOUD_PRINTER_OFFLINE
  | ApiErrorCode.CLOUD_PRINTER_ONLINE_STATUS_UNKNOWN
  | ApiErrorCode.CLOUD_PRINTER_BINDING_RECOVERY_REQUIRED
  | ApiErrorCode.CLOUD_PRINTER_COMPENSATION_RECOVERY_REQUIRED
  | ApiErrorCode.CLOUD_PRINTER_RECOVERY_REQUIRED
  | ApiErrorCode.CLOUD_PRINTER_VENDOR_REJECTED
  | ApiErrorCode.CLOUD_PRINTER_VENDOR_UNAVAILABLE
  | ApiErrorCode.IDEMPOTENCY_CONFLICT
  | ApiErrorCode.IDEMPOTENCY_IN_PROGRESS
  | ApiErrorCode.IDEMPOTENCY_RESULT_UNKNOWN;

export type ApiError = {
  code: ApiErrorCode;
  message: string;
  requestId?: string;
  details?: Record<string, unknown>;
};
